# Generated by Django 4.1.4 on 2023-01-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roomates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(default='Null', max_length=30)),
                ('religion', models.CharField(default='Null', max_length=30)),
                ('lodgerent', models.CharField(default='Null', max_length=30)),
                ('location', models.CharField(default='Null', max_length=100)),
                ('pic', models.CharField(default='Null', max_length=100)),
                ('lodgetype', models.CharField(default='Null', max_length=30)),
                ('price', models.CharField(default='Null', max_length=15)),
                ('Tiled', models.CharField(default='Null', max_length=15)),
                ('light', models.CharField(default='Null', max_length=15)),
                ('status', models.CharField(default='Null', max_length=100)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'roomates',
            },
        ),
    ]
