# Generated by Django 4.1.4 on 2023-01-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0002_roomates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomates',
            name='pic',
            field=models.CharField(blank=True, default='Null', max_length=100, null=True),
        ),
    ]
