# Generated by Django 4.1.4 on 2023-01-03 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0003_alter_roomates_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomates',
            old_name='price',
            new_name='pricesharing',
        ),
        migrations.RemoveField(
            model_name='roomates',
            name='status',
        ),
    ]
