# Generated by Django 4.1.4 on 2023-01-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0004_rename_price_roomates_pricesharing_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomates',
            old_name='Tiled',
            new_name='tiled',
        ),
        migrations.AddField(
            model_name='roomates',
            name='water',
            field=models.CharField(default='Null', max_length=15),
        ),
    ]
