# Generated by Django 4.1.4 on 2023-01-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0005_rename_tiled_roomates_tiled_roomates_water'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomates',
            name='phone',
            field=models.CharField(default='Null', max_length=30),
        ),
    ]
