# Generated by Django 4.1.4 on 2023-01-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0006_roomates_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='lodgepics',
            name='picname',
            field=models.FileField(blank=True, default='Null', null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='roomates',
            name='phone',
            field=models.CharField(blank=True, default='Null', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='roomates',
            name='pic',
            field=models.ImageField(blank=True, default='Null', null=True, upload_to='media'),
        ),
    ]
