# Generated by Django 4.1.4 on 2023-01-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0007_alter_agents_pic_alter_lodgepics_picname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='pic',
            field=models.FileField(blank=True, default='Null', null=True, upload_to='media/'),
        ),
    ]
