# Generated by Django 4.1.4 on 2023-01-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0009_alter_roomates_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=20)),
                ('amount', models.IntegerField(default=1000)),
                ('state', models.CharField(default='enter state', max_length=150)),
            ],
            options={
                'db_table': 'customer_infos',
            },
        ),
    ]
