# Generated by Django 4.1.4 on 2023-01-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0011_rename_firstname_customerinfo_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
