# Generated by Django 4.1.4 on 2023-01-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0013_alter_customerinfo_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='amount',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='fullname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
