# Generated by Django 4.1.4 on 2023-01-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0014_alter_customerinfo_amount_alter_customerinfo_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomates',
            name='pic1',
            field=models.FileField(blank=True, default='Null', null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='roomates',
            name='pic2',
            field=models.FileField(blank=True, default='Null', null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='roomates',
            name='pic3',
            field=models.FileField(blank=True, default='Null', null=True, upload_to='media/'),
        ),
    ]
