# Generated by Django 4.1.4 on 2023-01-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0016_customerinfo_payfor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('pwd', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'myadmin',
            },
        ),
    ]
