# Generated by Django 4.1.4 on 2023-01-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0017_myadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
