# Generated by Django 4.1.4 on 2023-01-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0019_agents_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspectionhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_inspection', models.DateTimeField(auto_now_add=True)),
                ('studentname', models.CharField(blank=True, max_length=150, null=True)),
                ('studentphone', models.CharField(blank=True, max_length=150, null=True)),
                ('studentemail', models.CharField(blank=True, max_length=150, null=True)),
                ('lodgename', models.CharField(blank=True, max_length=150, null=True)),
                ('lodgeid', models.CharField(blank=True, max_length=150, null=True)),
                ('inspection_status', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
