# Generated by Django 4.1.4 on 2023-01-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0021_rename_inspectionhistory_schedule_inspection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_inspection',
            name='timeof_inspection',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='schedule_inspection',
            name='date_of_inspection',
            field=models.DateField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='schedule_inspection',
            name='inspection_status',
            field=models.CharField(blank=True, default='inprogress', max_length=150, null=True),
        ),
    ]
