# Generated by Django 4.1.4 on 2023-01-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0022_schedule_inspection_timeof_inspection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomates',
            name='name',
            field=models.CharField(blank=True, default='Null', max_length=30, null=True),
        ),
    ]
