# Generated by Django 4.1.4 on 2023-01-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0023_roomates_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roomymatching_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(blank=True, max_length=150, null=True)),
                ('owner_phone', models.CharField(blank=True, max_length=150, null=True)),
                ('seeker_name', models.CharField(blank=True, max_length=150, null=True)),
                ('seeker_phone', models.CharField(blank=True, max_length=150, null=True)),
                ('date_ofmeeting', models.DateField(blank=True, max_length=150, null=True)),
                ('time_ofmeeting', models.CharField(blank=True, max_length=150, null=True)),
                ('match_status', models.CharField(blank=True, default='inprogress', max_length=150, null=True)),
            ],
        ),
    ]
