# Generated by Django 4.1.4 on 2023-01-26 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0024_roomymatching_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomates',
            old_name='name',
            new_name='fullname',
        ),
    ]
