# Generated by Django 4.1.4 on 2023-02-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0025_rename_name_roomates_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodges',
            name='fenced',
            field=models.CharField(default='Null', max_length=15),
        ),
    ]
