# Generated by Django 4.1.4 on 2023-02-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0026_lodges_fenced'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='address',
            field=models.CharField(blank=True, default='Null', max_length=20, null=True),
        ),
    ]
