# Generated by Django 4.1.4 on 2023-02-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0027_schools_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosting_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(default='Null', max_length=30)),
                ('fullname', models.CharField(blank=True, default='Null', max_length=30, null=True)),
                ('phone', models.CharField(blank=True, default='Null', max_length=30, null=True)),
                ('location', models.CharField(default='Null', max_length=100)),
                ('lodgetype', models.CharField(default='Null', max_length=30)),
                ('hostprice', models.CharField(default='Null', max_length=15)),
                ('tiled', models.CharField(default='Null', max_length=15)),
                ('light', models.CharField(default='Null', max_length=15)),
                ('water', models.CharField(default='Null', max_length=15)),
                ('bankname', models.CharField(default='Null', max_length=15)),
                ('accountnumber', models.CharField(default='Null', max_length=15)),
                ('accountname', models.CharField(default='Null', max_length=15)),
                ('pic1', models.FileField(blank=True, default='Null', null=True, upload_to='media/')),
                ('pic2', models.FileField(blank=True, default='Null', null=True, upload_to='media/')),
                ('pic3', models.FileField(blank=True, default='Null', null=True, upload_to='media/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hosting_table',
            },
        ),
    ]
