# Generated by Django 4.1.4 on 2023-02-01 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0029_rename_hosting_table_hosts'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hosts',
            table='hosts',
        ),
    ]
