# Generated by Django 4.1.4 on 2023-02-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0030_alter_hosts_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='accountname',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='accountnumber',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='bankname',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='fullname',
            field=models.CharField(blank=True, default='Null', max_length=100, null=True),
        ),
    ]
