# Generated by Django 4.1.4 on 2023-02-02 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0031_alter_hosts_accountname_alter_hosts_accountnumber_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roomymatching_table',
            table='roomymatching_table',
        ),
    ]
