# Generated by Django 4.1.4 on 2023-07-28 03:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enema', '0032_alter_roomymatching_table_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='pic',
            field=cloudinary.models.CloudinaryField(default='Null', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='pic1',
            field=cloudinary.models.CloudinaryField(default='Null', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='pic2',
            field=cloudinary.models.CloudinaryField(default='Null', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='pic3',
            field=cloudinary.models.CloudinaryField(default='Null', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='lodgepics',
            name='picname',
            field=cloudinary.models.CloudinaryField(default='Null', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='roomates',
            name='pic',
            field=cloudinary.models.CloudinaryField(default='Null', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='roomates',
            name='pic1',
            field=cloudinary.models.CloudinaryField(default='Null', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='roomates',
            name='pic2',
            field=cloudinary.models.CloudinaryField(default='Null', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='roomates',
            name='pic3',
            field=cloudinary.models.CloudinaryField(default='Null', max_length=255, verbose_name='image'),
        ),
    ]
